name: Homework Tests

on:
  pull_request:
    paths:
      - 'homework/**'  # Запускать workflow только при изменении файлов в 'homework'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.18'  # Укажите вашу версию Go

      - name: Install Dependencies
        working-directory: homework
        run: go mod download

      - name: Run Tests
        working-directory: homework
        run: go test -v ./...
